<?php
/**
 * Created by PhpStorm.
 * User: GermanWeb
 * Date: 26.09.2018
 * Time: 11:53
 */

$page = $variables['page'];

$settings = $this->getSettingsContainer('main_config');

$menu_items = $this->macros('menu', 'draw', array('footer-menu'))['item'];

$main_phone = $settings->getValue('main-phone');
$main_email = $settings->getValue('main-email');

foreach ($menu_items as $item) {
    if ($variables['request-uri'] == $item['link']) {
        $activeClass = 'active';
        break;
    } else {
        $activeClass = '';
    }
}

?>

<div class="footer__content">
    <div class="footer__menu">
        <ul>
            <? foreach ($menu_items as $item): ?>
                <li class="<?= $item['status'] ?>">
                    <a href="<?= $item['link'] ?>">
                        <?= $item['name'] ?>
                    </a>
                </li>
            <? endforeach; ?>
        </ul>
    </div>

    <div class="footer__info">
        <h3>Соболевский муниципальный район</h3>

        <span class="footer__date">2014-<?= date("Y") ?></span>

        <div class="footer__contacts">
            <div class="footer__phone">
                <a href="tel:<?= $main_phone ?>">
                    <p>Телефон</p>
                    <?= $main_phone ?>
                </a>
            </div>
            <div class="footer__mail">
                <a href="mailto:<?= $main_email ?>">
                    <p>Почта</p>
                    <?= $main_email ?>
                </a>
            </div>
        </div>

        <span class="footer__separate"></span>

        <p class="footer__prompt">
            Если Вы заметили опечатку или неточность - выделите текст и нажмите: Ctrl+Enter
        </p>
    </div>
</div>
