<?php
/**
 * @var umiTemplaterPHP|ViewPhpExtension|DemomarketPhpExtension $this
 * @var array $variables
 */
?>

<?//= $this->render($variables, 'layout/modal/index') ?>
<?//= $this->render($variables, 'layout/header/mobile') ?>
<?//= $this->render($variables, 'layout/header/mobile_menu') ?>

<header class="bounceInDown">
	<?= $this->render($variables, 'layout/header/top') ?>
	<?= $this->render($variables, 'layout/header/menu') ?>
</header>
