<?php
/**
 * Created by PhpStorm.
 * User: GermanWeb
 * Date: 03.09.2018
 * Time: 10:44
 */

$settings = $this->getSettingsContainer('main_config');
$page = $variables['page'];

$lang = $variables['lang'];

$collection = langsCollection::getInstance()->getList();

$main_address = $settings->getValue('main-address');
$main_phone = $settings->getValue('main-phone');
$main_email = $settings->getValue('main-email');

$url_logo = $this->render(
    [
        'id' => $settings->getId(),
        'field_name' => 'logo2',
        'src' => $settings->getValue('logo2'),
        'alt' => "logo",
        'width' => 295,
        'height' => 100,
    ],
    'library/thumbnail'
);

$menu_items = $this->macros('menu', 'draw', array('main-menu'))['item'];

foreach ($menu_items as $item) {
    if ($variables['request-uri'] == $item['link']) {
        $activeClass = 'active';
        break;
    } else {
        $activeClass = '';
    }
}


?>

<div class="header-top">

    <div class="header-top__logo">
        <a href="../../../../../index.php">
            <?= $url_logo ?>
        </a>
    </div>

    <div class="flag-block header-top__flag-block">
        <div class="flags header-top__flags">
            <p>язык</p>
            <img class="flag flag__ru" src="/images/images-kamchatka/flags/russia.svg" alt="rus">
            <img class="flag flag__en" src="/images/images-kamchatka/flags/united-kingdom.svg" alt="eng">
        </div>

        <select name="select-box" id="selectId" class="select" lang_page="<?= $lang ?>">
            <option value="ru" name="value">РУС</option>
            <option value="en" name="value">ENG</option>
        </select>
    </div>

    <div class="map-site header-top__map-site">
        <a href="/">
            <span class="map-site__image flaticon-diagram"></span>
            <p class="map-site__text">
                Карта сайта
            </p>
        </a>
    </div>

    <div class="address header-top__address">
        <p class="address__text header-top__text">
            <?= $main_address ?>
        </p>

        <div class="address__link header-top__link">
            <a class="address__phone" href="tel:<?= $main_phone ?>">
                <?= $main_phone ?>
            </a>
            <a class="address__mail" href="mailto:<?= $main_email ?>">
                <?= $main_email ?>
            </a>
        </div>
    </div>

    <div class="eyeglasses header-top__eyeglasses">
        <a href="/">
            <span class="eyeglasses__image flaticon-glasses"></span>
            <p class="eyeglasses__text">
                Версия для слабовидящих
            </p>
        </a>
    </div>

    <nav class="mobile-nav">
        <div class="mobile-nav__container">
            <ul class="mobile-menu">
                <div class="mobile-menu__icon">
                    <span></span>
                    <span></span>
                    <span></span>
                    <span></span>
                </div>
            </ul>
        </div>
    </nav>

    <div class="buttonSearch buttonSearch__mobile-top">
        <form method="get">
            <button type="button" class="btn btn1 btn-default">
                <span class="flaticon-magnifying-glass"></span>
                <span class="flaticon-close"></span>
            </button>
        </form>
    </div>
</div>

<div class="buttonSearch buttonSearch__mobile-bottom">
    <form method="get">
        <input type="text" placeholder="Искать здесь...">

        <button type="submit" class="btn btn2 btn-default">
            <span class="flaticon-magnifying-glass"></span>
        </button>
    </form>
</div>

<nav class="mobile-nav">
    <div class="mobile-nav__container">
        <ul class="mobile-menu">
            <ul class="mobile-menu__links">
                <? foreach ($menu_items as $item): ?>
                    <li class="mobile-menu__links-item <?= $item['status'] ?>">
                        <a href="<?= $item['link'] ?>">
                            <?= $item['name'] ?>
                        </a>
                    </li>
                <? endforeach; ?>
            </ul>
        </ul>
    </div>
</nav>
















