<?php
/**
 * Created by PhpStorm.
 * User: GermanWeb
 * Date: 19.02.2019
 * Time: 11:06
 */

$page = $variables['page'];

$pageContent = $page->getValue('content');
$pageTabs = $page->getValue('appeal-procedure_tabs');

$pageOneTab = [];
foreach ($pageTabs as $key1 => $item1) {
    $pageOneTab[$key1]['title'] = $this->getObjectById($item1)->name;
    $extraTabs = $this->getObjectById($item1)->getValue('appeal-procedure_inside-tabs');

    foreach ($extraTabs as $key2 => $item2) {
        $pageOneTab[$key1]['extra-tab'][$key2]['extra-title'] = $this->getObjectById($item2)->name;
        $pageOneTab[$key1]['extra-tab'][$key2]['extra-text'] = $this->getObjectById($item2)->getValue('appeal-procedure_extra-text');
    }
}

?>

<div class="public-hearing-page">

    <?= $pageContent ?>

    <span class="tabs__button">
        <span class="button-text active-one">Открыть все вкладки</span>
        <span class="button-text two">Закрыть все вкладки</span>
        <span class="flaticon-back active"></span>
    </span>

    <div class="charter-tabs">
        <?php foreach($pageOneTab as $key1 => $item1): ?>

            <div class="one-tab">
                <div class="one-tab__title">
                    <p>
                        <?= $item1['title'] ?>
                    </p>

                    <span class="flaticon-minus-horizontal-straight-line"></span>
                </div>

                <div class="one-tab__text">
                    <div class="main-text">
                        <?= $item1['text'] ?>
                    </div>

                    <?php foreach($pageOneTab[$key1]['extra-tab'] as $key2 => $item2): ?>
                        <div class="extra-tab extra-tab-id<?= $key2 ?>">
                            <div class="extra-tab__title">
                                <p>
                                    <?= $item2['extra-title'] ?>
                                </p>

                                <span class="flaticon-back"></span>
                            </div>

                            <div class="extra-tab__text">
                                <?= $item2['extra-text'] ?>
                            </div>
                        </div>
                    <?php endforeach;?>
                </div>
            </div>

        <?php endforeach;?>
    </div>
</div>