<?php
/**
 * Created by PhpStorm.
 * User: GermanWeb
 * Date: 19.09.2018
 * Time: 16:03
 */

$page = $variables['page'];

$activities = $page->getValue('activities');

foreach ($activities as $key => $item) {
    $tabs[$key]['title'] = $this->getObjectById($item)->getName();
    $tabs[$key]['id'] = $this->getObjectById($item)->getId();
    $tabsTexts = $this->getObjectById($item)->getValue('activities_texts');

    foreach ($tabsTexts as $item_text) {
        $tabsTexts = $this->getObjectById($item_text)->getValue('activities_one-text');
        $tabs[$key]['text'][] = $tabsTexts;
    }
}

?>

<div class="activities home-page__activities wow bounceInUp">
    <div class="activities__title">
        <h3>Направления деятельности</h3>
    </div>

    <section class="activities__body">
        <div class="activities__left">
            <? foreach ($tabs as $key => $item): ?>
                <div class="activities__tab-link" data="id-<?= $item['id'] ?>">
                    <p><?= $item['title'] ?></p>
                </div>
            <? endforeach; ?>
        </div>

        <div class="activities__right">
            <? foreach ($tabs as $key => $item): ?>
            <div class="tab-body activities__tab-body d_none" data="id-<?= $item['id'] ?>">
                <div class="tab-body__header">
                    <p><?= $item['title'] ?>: популярные вопросы</p>

                    <div class="tab-body__link">
                        <a href="/">Подробнее</a>

                        <div class="flat-arrow">
                            <span class="flaticon-next-1"></span>
                            <span class="flaticon-next-1 flat-arrow_middle"></span>
                            <span class="flaticon-next-1"></span>
                        </div>
                    </div>
                </div>

                <div class="tab-body__main">
                    <? foreach ($tabs[$key]['text'] as $item_text): ?>
                        <div class="tab-body__text">
                                <?= $item_text ?>
                        </div>
                    <? endforeach; ?>
                </div>
            </div>
        <? endforeach; ?>
        </div>
    </section>
</div>
