<?php
/**
 * Created by PhpStorm.
 * User: GermanWeb
 * Date: 26.09.2018
 * Time: 12:05
 */

$page = $variables['page'];

$page_documents = $this->getPageById(8);
$documents = $page_documents->getValue('documents');

foreach ($documents as $key => $item) {
    $arr1[$key] = $this->getObjectById($item)->getValue('date-doc')->getFormattedDate('d.m.Y');
    $arr2[$key] = $this->getObjectById($item)->getName();
    $arr3[$key] = $this->getObjectById($item)->getValue('file-doc')->getFilePath(true);
    $arr4[$key] = $this->getObjectById($item)->getValue('img-doc')->getFilePath(true);
}

array_multisort($arr1, SORT_DESC, $arr2, $arr3, $arr4);

foreach ($arr1 as $key => $item) {
    $arr[$key]['date-doc'] = $item;
}

foreach ($arr2 as $key => $item) {
    $arr[$key]['title-doc'] = $item;
}

foreach ($arr3 as $key => $item) {
    $arr[$key]['file-doc'] = $item;
}

foreach ($arr4 as $key => $item) {
    $arr[$key]['img-doc'] = $item;
}

$arr = array_slice($arr,0,6);

?>

<div class="home-page__container-footer wow bounceInUp">
    <div class="documents home-page__documents">
        <div class="documents__title">
            <div class="documents__title-left">
                <h3>Новые документы</h3>
            </div>

            <div class="documents__title-right">
                <a href="/">Смотреть все

                    <div class="flat-arrow">
                        <span class="flaticon-next-1"></span>
                        <span class="flaticon-next-1 flat-arrow_middle"></span>
                        <span class="flaticon-next-1"></span>
                    </div>
                </a>
            </div>
        </div>

        <section class="documents__body">
            <? foreach ($arr as $key => $item): ?>
            <a href="<?= $item['file-doc'] ?>" class="one-document" download>
                <div class="one-document__img">
                    <img src="<?= $item['img-doc'] ?>" alt="doc">
                </div>

                <div class="one-document__footer">
                    <p class="one-document__text">
                        <?= $item['title-doc'] ?>
                    </p>

                    <span class="one-document__date">
                        <?= $item['date-doc'] ?>
                    </span>
                </div>
            </a>
            <? endforeach; ?>
        </section>
    </div>

</div>
