<?php
/**
 * Created by PhpStorm.
 * User: GermanWeb
 * Date: 26.09.2018
 * Time: 12:05
 */

?>

<div class="home-page__container-footer">
    <div class="documents home-page__documents">
        <div class="documents__title">
            <div class="documents__title-left">
                <h3>Новые документы</h3>
            </div>

            <div class="documents__title-right">
                <a href="/">Смотреть все

                    <div class="flat-arrow">
                        <span class="flaticon-next-1"></span>
                        <span class="flaticon-next-1 flat-arrow_middle"></span>
                        <span class="flaticon-next-1"></span>
                    </div>
                </a>
            </div>
        </div>

        <section class="documents__body">
            <div class="one-document">
                <div class="one-document__img">
                    <img src="/images/images-kamchatka/documents/word.png" alt="doc">
                </div>

                <div class="one-document__footer">
                    <p class="one-document__text">
                        Lorem ipsum dolor sit.
                    </p>

                    <span class="one-document__date">
                        28.02.2018
                    </span>
                </div>
            </div>

            <div class="one-document">
                <div class="one-document__img">
                    <img src="/images/images-kamchatka/documents/word.png" alt="doc">
                </div>

                <div class="one-document__footer">
                    <p class="one-document__text">
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit,
                        sed do eiusmod tempor incididunt ut labore et
                        dolore magna aliqua.
                    </p>

                    <span class="one-document__date">
                        28.02.2018
                    </span>
                </div>
            </div>

            <div class="one-document">
                <div class="one-document__img">
                    <img src="/images/images-kamchatka/documents/word.png" alt="doc">
                </div>

                <div class="one-document__footer">
                    <p class="one-document__text">
                        Lorem ipsum dolor sit amet, consectetur.
                    </p>

                    <span class="one-document__date">
                        28.02.2018
                    </span>
                </div>
            </div>

            <div class="one-document">
                <div class="one-document__img">
                    <img src="/images/images-kamchatka/documents/pdf.png" alt="doc">
                </div>

                <div class="one-document__footer">
                    <p class="one-document__text">
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit,
                        sed do eiusmod tempor incididunt ut labore et
                        dolore magna aliqua.
                    </p>

                    <span class="one-document__date">
                        28.02.2018
                    </span>
                </div>
            </div>

            <div class="one-document">
                <div class="one-document__img">
                    <img src="/images/images-kamchatka/documents/word.png" alt="doc">
                </div>

                <div class="one-document__footer">
                    <p class="one-document__text">
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                    </p>

                    <span class="one-document__date">
                        28.02.2018
                    </span>
                </div>
            </div>

            <div class="one-document">
                <div class="one-document__img">
                    <img src="/images/images-kamchatka/documents/pdf.png" alt="doc">
                </div>

                <div class="one-document__footer">
                    <p class="one-document__text">
                        Lorem ipsum dolor sit amet, consectetur adipiscing.
                    </p>

                    <span class="one-document__date">
                        28.02.2018
                    </span>
                </div>
            </div>
        </section>
    </div>

</div>
