<?php
/**
 * Created by PhpStorm.
 * User: GermanWeb
 * Date: 26.09.2018
 * Time: 12:05
 */

$page = $variables['page'];
$settings = $this->getSettingsContainer('main_config');

$main_image['doc'] = $settings->getValue('main_doc-img')->getFilePath(true);
$main_image['pdf'] = $settings->getValue('main_pdf-img')->getFilePath(true);

$page_documents = $this->getPageById(8);
$documents = $page_documents->getValue('documents');
$arr1 = [];
$arr2 = [];
$arr3 = [];
$arr4 = [];
$arr5 = [];

foreach ($documents as $key => $item) {
    $dateDoc = $this->getObjectById($item)->getValue('date-doc');
    isset($dateDoc) ? $arr1[$key] = $dateDoc->getFormattedDate('d.m.Y') : null;

    $arr2[$key] = $this->getObjectById($item)->name;

    $fileDoc = $this->getObjectById($item)->getValue('file-doc');
    isset($fileDoc) ? $arr3[$key] = $fileDoc->getFilePath(true) : null;

    $docFormatId = $this->getObjectById($item)->getValue('format_doc');
    $docFormatName = $this->getObjectById($docFormatId)->name;

    if (isset($docFormatId)) {
        $arr4[$key] = $main_image[$docFormatName];

    } else {
        $arr4[$key] = $main_image['doc'];
    }

    $arr5[$key] = $this->getObjectById($item)->getValue('type-doc');
}


array_multisort($arr1, SORT_DESC, $arr2, $arr3, $arr4, $arr5);

foreach ($arr1 as $key => $item) $arr[$key]['date-doc'] = $item;
foreach ($arr2 as $key => $item) $arr[$key]['title-doc'] = $item;
foreach ($arr3 as $key => $item) $arr[$key]['file-doc'] = $item;
foreach ($arr4 as $key => $item) $arr[$key]['img-doc'] = $item;
foreach ($arr5 as $key => $item) $arr[$key]['type-doc'] = $item;

$arr = array_slice($arr,0,6);
?>

<div class="home-page__container-footer">
    <div class="documents home-page__documents">
        <div class="documents__title">
            <div class="documents__title-left wow bounceInLeft">
                <h3>Новые документы</h3>
            </div>

            <div class="documents__title-right wow bounceInRight">
                <a href="/">Смотреть все

                    <div class="flat-arrow">
                        <span class="flaticon-next-1"></span>
                        <span class="flaticon-next-1 flat-arrow_middle"></span>
                        <span class="flaticon-next-1"></span>
                    </div>
                </a>
            </div>
        </div>

        <section class="documents__body wow bounceInUp">
            <? foreach ($arr as $key => $item): ?>
            <a href="<?= $item['file-doc'] ?>" class="one-document" download>
                <div class="one-document__img">
                    <img src="<?= $item['img-doc'] ?>" alt="doc">
                </div>

                <div class="one-document__footer">
                    <p class="one-document__text">
                        <?= $item['title-doc'] ?>
                    </p>

                    <span class="one-document__date">
                        <?= $item['date-doc'] ?>
                    </span>
                </div>
            </a>
            <? endforeach; ?>
        </section>
    </div>
</div>
