<?php
/**
 * Created by PhpStorm.
 * User: GermanWeb
 * Date: 26.09.2018
 * Time: 10:38
 */
?>

<div class="links home-page__links">
    <div class="links__title">
        <h3>Полезные <span>ссылки</span></h3>
    </div>

    <section class="links__body">
        <a href="/" class="one-link" style="background-image: url('/images/images-kamchatka/links/bear.png')">

            <p class="one-link__text">
                Lorem ipsum dolor sit amet
            </p>

            <div class="one-link__footer">
                <span class="flaticon-link"></span>
                <p>
                    example.ru
                </p>
            </div>
        </a>
        <a href="/" class="one-link" style="background-image: url('/images/images-kamchatka/links/bear.png')">

            <p class="one-link__text">
                Lorem ipsum dolor sit amet
            </p>

            <div class="one-link__footer">
                <span class="flaticon-link"></span>
                <p>
                    example.ru
                </p>
            </div>
        </a>
        <a href="/" class="one-link" style="background-image: url('/images/images-kamchatka/links/bear.png')">

            <p class="one-link__text">
                Lorem ipsum dolor sit amet
            </p>

            <div class="one-link__footer">
                <span class="flaticon-link"></span>
                <p>
                    example.ru
                </p>
            </div>
        </a>
        <a href="/" class="one-link" style="background-image: url('/images/images-kamchatka/links/bear.png')">

            <p class="one-link__text">
                Lorem ipsum dolor sit amet
            </p>

            <div class="one-link__footer">
                <span class="flaticon-link"></span>
                <p>
                    example.ru
                </p>
            </div>
        </a>
        <a href="/" class="one-link" style="background-image: url('/images/images-kamchatka/links/bear.png')">

            <p class="one-link__text">
                Lorem ipsum dolor sit amet
            </p>

            <div class="one-link__footer">
                <span class="flaticon-link"></span>
                <p>
                    example.ru
                </p>
            </div>
        </a>
    </section>
</div>
