<?php
/**
 * Created by PhpStorm.
 * User: GermanWeb
 * Date: 07.09.2018
 * Time: 14:42
 */

$settings = $this->getSettingsContainer('main_config');
$settings->getValue('sobolevo-prefix');

$cityPoint = [];
$cityPoint[0]['active'] = 'active';
$cityPoint[0]['class_name'] = 'sobolevo';
$cityPoint[0]['title'] = $settings->getValue('sobolevo-prefix');
$cityPoint[0]['area'] = $settings->getValue('sobolevo-area');
$cityPoint[0]['population'] = $settings->getValue('sobolovo-population');
$cityPoint[0]['link_map'] = $settings->getValue('sobolevo-link_map');

$cityPoint[1]['active'] = '';
$cityPoint[1]['class_name'] = 'ustevo';
$cityPoint[1]['title'] = $settings->getValue('ustevo-prefix');
$cityPoint[1]['area'] = $settings->getValue('ustevo-area');
$cityPoint[1]['population'] = $settings->getValue('ustevo-population');
$cityPoint[1]['link_map'] = $settings->getValue('ustevo-link_map');

$cityPoint[2]['active'] = '';
$cityPoint[2]['class_name'] = 'krutogorovo';
$cityPoint[2]['title'] = $settings->getValue('krutogorovo-prefix');
$cityPoint[2]['area'] = $settings->getValue('krutogorovo-area');
$cityPoint[2]['population'] = $settings->getValue('krutogorovo-population');
$cityPoint[2]['link_map'] = $settings->getValue('krutogorovo-link_map');

$cityPoint[3]['active'] = '';
$cityPoint[3]['class_name'] = 'ichinsky';
$cityPoint[3]['title'] = $settings->getValue('ichinsky-prefix');
$cityPoint[3]['area'] = $settings->getValue('ichinsky-area');
$cityPoint[3]['population'] = $settings->getValue('ichinsky-population');
$cityPoint[3]['link_map'] = $settings->getValue('ichinsky-link_map');

$objectsCollection = umiObjectsCollection::getInstance();
$arrAreaMap = $objectsCollection->getGuidedItems(388);

?>

<div class="tabs home-page__tabs">
    <nav>
        <ul class="tabs__link">
            <li class="tab-link tab-link-one wow bounceInLeft">
                <span class="flaticon-placeholder"></span>
                <span class="tab-link__background"></span>
                <p>Карта района</p>
            </li>
            <li class="tab-link tab-link-two wow bounceInDown">
                <span class="flaticon-cloudy"></span>
                <span class="tab-link__background"></span>
                <p>Климат</p>
            </li>
            <li class="tab-link tab-link-three wow bounceInRight">
                <span class="flaticon-child"></span>
                <span class="tab-link__background"></span>
                <p>Население</p>
            </li>
        </ul>
    </nav>

    <section class="tabs__body wow bounceInUp">
        <div class="tab tab-one">
            <div class="tab-one__left">
                <img src="/images/images-kamchatka/map/home-page-map.svg" alt="map">

                <? foreach ($cityPoint as $key => $item): ?>
                    <div class="map-item city-<?= $item['class_name'] ?> <?= $item['active'] ?> ">
                        <span class="flaticon-dot"></span>

                        <div class="map-item__title">
                            <p>
                                <?= $item['title'] ?>
                            </p>

                            <span class="map-item__line"></span>
                        </div>
                    </div>
                <? endforeach; ?>

                <!-- Дополнительные населенные пункты карты -->
                <div class="map-item__add-area">
                    <? foreach ($arrAreaMap as $key => $item): ?>
                        <span class="item-id-<?= $key ?>"><?= $item ?></span>
                    <? endforeach; ?>
                </div>
            </div>

            <div class="tab-one__right">
                <? foreach ($cityPoint as $key => $item): ?>
                    <div class="city city-<?= $item['class_name'] ?> <?= $item['active'] ?> ">
                        <div class="wrapper">
                            <h3>
                                <?= $item['title'] ?>
                            </h3>

                            <div>
                                <span class="flaticon-map-location"></span>

                                <p>
                                <span>
                                    Площадь -
                                </span>

                                    <?= $item['area'] ?> км<sup>2</sup>
                                </p>
                            </div>

                            <div>
                                <span class="flaticon-multiple-users-silhouette"></span>

                                <p>
                                <span>
                                    Население -
                                </span>

                                    <?= $item['population'] ?> человек
                                </p>
                            </div>

                            <div>
                                <span class="flaticon-grid-world"></span>

                                <a href="<?= $item['link_map'] ?>">
                                    <?= $item['link_map'] ?>
                                </a>
                            </div>
                        </div>
                    </div>
                <? endforeach; ?>
            </div>
        </div>

        <div class="tab tab-two d_none">
            <div class="tab-two__weather">
                <img src="/images/images-kamchatka/weather.png" alt="weather">
            </div>
        </div>

        <div class="tab tab-three d_none">
            <div class="tab-three__text">
                <p>
                    <?= $settings->getValue('population_text') ?>
                </p>
            </div>

            <div class="tab-three__diagram">
                <div
                        class='tab-three__regions'
                        data-sobolevo='<?= $settings->getValue('sobolevo-prefix') ?> <?= $settings->getValue('sobolovo-population') ?>чел.'
                        data-sobolevo_population='<?= $settings->getValue('sobolovo-population') ?>'
                        data-ustevo='<?= $settings->getValue('ustevo-prefix') ?> <?= $settings->getValue('ustevo-population') ?>чел.'
                        data-ustevo_population='<?= $settings->getValue('ustevo-population') ?>'
                        data-krutogorovo='<?= $settings->getValue('krutogorovo-prefix') ?> <?= $settings->getValue('krutogorovo-population') ?>чел.'
                        data-krutogorovo_population='<?= $settings->getValue('krutogorovo-population') ?>'
                        data-ichinsky='<?= $settings->getValue('ichinsky-prefix') ?> <?= $settings->getValue('ichinsky-population') ?>чел.'
                        data-ichinsky_population='<?= $settings->getValue('ichinsky-population') ?>'
                ></div>

                <div id="donutchart" style="width: 100%; height: 100%;"></div>

                <span class="all_population"></span>
            </div>

            <div class="tab-three__mobile-text">
                <p>
                    <?= $settings->getValue('sobolevo-prefix') ?>
                    -
                    <?= $settings->getValue('sobolovo-population') ?>
                    чел.
                </p>

                <p>
                    <?= $settings->getValue('ustevo-prefix') ?>
                    -
                    <?= $settings->getValue('ustevo-population') ?>
                    чел.
                </p>

                <p>
                    <?= $settings->getValue('krutogorovo-prefix') ?>
                    -
                    <?= $settings->getValue('krutogorovo-population') ?>
                    чел.
                </p>

                <p>
                    <?= $settings->getValue('ichinsky-prefix') ?>
                    -
                    <?= $settings->getValue('ichinsky-population') ?>
                    чел.
                </p>
            </div>
        </div>
    </section>
</div>