<?php
/**
 * Список последних новостей на главной.
 *
 * @var umiTemplaterPHP|ViewPhpExtension|DemomarketPhpExtension $this
 * @var array $variables
 * @var array $newsItemList
 */

$lastNews = $this->getLastNews();
$newsItemList = $lastNews['items'];
?>

<?php if (count($newsItemList) > 0): ?>
	<div class="news_content clearfix"
	     umi:element-id="<?= $lastNews['category_id'] ?>"
	     umi:region="list"
	     umi:sortable="none"
	     umi:module="news"
	     umi:method="lastlist"
	     umi:button-position="top right"
	>
		<?php foreach ($newsItemList as $newsItem): ?>
			<?= $this->render($this->getPageById($newsItem['id']), 'content/home/news/item') ?>
		<?php endforeach; ?>
	</div>
<?php endif; ?>
