<?php
/**
 * Страница контента.
 * Страница по умолчанию обрабатывается по отдельному шаблону `content/home/index`.
 *
 * @var umiTemplaterPHP|ViewPhpExtension|DemomarketPhpExtension $this
 * @var array $variables
 * @var iUmiHierarchyElement $page
 */

$page = $variables['page'];
$settings = $this->getSettingsContainer('main_config');

// Получени type id через umiHierarchy(старый код)
//$element = umiHierarchy::getInstance()->getElement($page->id);
//$objects = umiObjectsCollection::getInstance();
//if ($element) {
//    $pageObjectId = $element->getObjectId();
//    $pageTypeId = $objects->getObject($pageObjectId)->getTypeId();
//}

$pageTypeId = $page->getObjectTypeId();

$area_insidePages = array(132, 134, 135, 136, 137, 138, 139, 427, 428);

$administration_insidePages = range(150, 170);
$administration_insidePagesNewPage = range(176, 185);

$administration_insidePages = array_merge($administration_insidePages, $administration_insidePagesNewPage);
array_push($administration_insidePages, 386);
array_push($administration_insidePages, 416);

$departments_tabsPagesLevel1 = array(402, 408);

$departments_tabsPagesLevel2 = array(403, 404);

$documents_insidePages = range(391, 393);
array_push($documents_insidePages, 129);

$anti_corruption = range(418, 419);

$polls = array(420, 421, 423);

?>

<?php if ($this->isHomePage($variables)): ?>
    <?= $this->render($variables, 'content/home/index') ?>

<?php elseif (in_array($pageTypeId, $area_insidePages)): ?>
    <?= $this->render($variables, 'content/area/index') ?>

<?php elseif (in_array($pageTypeId, $administration_insidePages)): ?>
    <?= $this->render($variables, 'content/administration/index') ?>

<?php elseif (in_array($pageTypeId, $departments_tabsPagesLevel1)): ?>
    <?= $this->render($variables, 'content/administration/page-departments/index') ?>

<?php elseif (in_array($pageTypeId, $departments_tabsPagesLevel2)): ?>
    <?= $this->render($variables, 'content/administration/page-departments/inside-page/index') ?>

<?php elseif (in_array($pageTypeId, $documents_insidePages)): ?>
    <?= $this->render($variables, 'content/documents/index') ?>

<?php elseif (in_array($pageTypeId, $anti_corruption)): ?>
    <?= $this->render($variables, 'content/anti-corruption/index') ?>

<?php elseif (in_array($pageTypeId, $polls)): ?>
    <?= $this->render($variables, 'content/polls/folder-polls') ?>

<?php elseif (422 === $pageTypeId): ?>
    <?= $this->render($variables, 'content/polls/one-poll') ?>

<?php elseif ($this->is404Page($variables)): ?>
    <?= $this->render($variables, 'content/notfound') ?>

<?php else: ?>
    <?= $this->render($variables, 'layout/breadcrumbs') ?>

    <div class="section_capt">
        <div class="container">
            <div class="row">
                <div class="logo">
                    <?= $this->render(
                        [
                            'id' => $settings->getId(),
                            'field_name' => 'logo1',
                            'src' => $settings->getValue('logo1'),
                            'alt' => "logo",
                            'width' => 40,
                            'height' => 50,
                        ],
                        'library/thumbnail'
                    ) ?>
                </div>

                <h1 umi:element-id="<?= $page->getId() ?>"
                    umi:field-name="h1"
                    umi:empty="<?= $this->translate('empty_page_name') ?>"
                >
                    <?= $page->getValue('h1') ?>
                </h1>
            </div>

            <div class="title">
                <span class="flaticon-seo"></span>

                <h2>
                    Раздел находится в разработке
                </h2>
            </div>
        </div>
    </div>

<?php endif; ?>
