<?php
/**
 * Страница контента.
 * Страница по умолчанию обрабатывается по отдельному шаблону `content/home/index`.
 *
 * @var umiTemplaterPHP|ViewPhpExtension|DemomarketPhpExtension $this
 * @var array $variables
 * @var iUmiHierarchyElement $page
 */

$page = $variables['page'];

$settings = $this->getSettingsContainer('main_config');

$element = umiHierarchy::getInstance()->getElement($page->id);
$objects = umiObjectsCollection::getInstance();

if ($element) {
    $pageObjectId = $element->getObjectId();
    $pageTypeId = $objects->getObject($pageObjectId)->getTypeId();
}

$area_insidePages = array(132, 134, 135, 136, 137, 138, 139);

?>

<?php if ($this->isHomePage($variables)): ?>
    <?= $this->render($variables, 'content/home/index') ?>

<?php elseif ( in_array($pageTypeId, $area_insidePages)):?>
    <?= $this->render($variables, 'content/area/index') ?>

<?php elseif ($this->is404Page($variables)): ?>
    <?= $this->render($variables, 'content/notfound') ?>

<?php else: ?>

    <?= $this->render($variables, 'layout/breadcrumbs') ?>

    <div class="section_capt">
        <div class="container">
            <div class="row">
                <div class="logo">
                    <?= $this->render(
                        [
                            'id' => $settings->getId(),
                            'field_name' => 'logo1',
                            'src' => $settings->getValue('logo1'),
                            'alt' => "logo",
                            'width' => 40,
                            'height' => 50,
                        ],
                        'library/thumbnail'
                    ) ?>
                </div>

                <h1 umi:element-id="<?= $page->getId() ?>"
                    umi:field-name="h1"
                    umi:empty="<?= $this->translate('empty_page_name') ?>"
                >
                    <?= $page->getValue('h1') ?>
                </h1>
            </div>
        </div>
    </div>

    <div class="container grey_border"
         umi:element-id="<?= $page->getId() ?>"
         umi:field-name="content"
         umi:empty="<?= $this->translate('empty_page_content') ?>"
    >
        <?= $page->getValue('content') ?>
    </div>
<?php endif; ?>
