<?php
/**
 * Страница 404.
 *
 * @var umiTemplaterPHP|ViewPhpExtension|DemomarketPhpExtension $this
 * @var array $variables
 */

$page = $this->getPageById(47);

?>

<div class="page404">
    <div class="page404__body">
        <div class="page404__text">
            <h3>
                <?= $page->getValue('h1') ?>
            </h3>

            <p>
                <?= $page->getValue('content') ?>
            </p>
        </div>

        <div class="page404__link">
            <a href="<?= $this->getHomePageUrl() ?>" class="page404__button main-button">
                <?= $this->translate('back_to_home_page') ?>
            </a>
        </div>
    </div>
</div>