<?php
/**
 * Created by PhpStorm.
 * User: GermanWeb
 * Date: 22.10.2018
 * Time: 14:33
 */
$page = $variables['page'];
$pageId = $page->id;
$pageTitle = $page->getValue('h1');
$pageLink = $page->link;
$pageAlt = $page->getAltName();
$pageContent = $page->getValue('content');

$pageArea_insidePages = $this->macros('content', 'menu', array(null, 1, 4))['items'];

$pageArea['id'] = $this->getPageById(4)->id;
$pageArea['name'] = $this->getPageById(4)->getValue('h1');
$pageArea['link'] = $this->getPageById(4)->link;

if ($pageLink == $pageArea['link']) {
    $pageArea['status'] = "active";
}

array_unshift($pageArea_insidePages, $pageArea);

?>

<?= $this->render($variables, 'content/header-pages') ?>

<div class="secondary-page area-page">
    <nav>
        <div class="secondary-page__mobile-menu">
            <span class="flaticon-angle-arrow-down"></span>
        </div>

        <ul class="secondary-page__menu">
            <? foreach($pageArea_insidePages as $key => $item): ?>
                <li class="secondary-page__item">
                    <a id="pageId-<?= $item['id'] ?>" class="<?= $item['status'] ?>" href="<?= $item['link'] ?>">
                        <?= $item['name'] ?>
                    </a>
                </li>
            <? endforeach; ?>
        </ul>
    </nav>

    <section class="one-page pageId-<?= $pageId ?>">
        <h2 umi:element-id="<?= $page->getId() ?>"
            umi:field-name="h1">
            <?= $pageTitle ?>
        </h2>

        <div class="one-page__body">

            <?php if ($pageLink == $pageArea['link']): ?>

                <div umi:element-id="<?= $page->getId() ?>"
                     umi:field-name="content"
                     class="about-area">
                    <?= $pageContent ?>
                </div>

            <?php else: ?>

                <?php if(file_exists(realpath(dirname(__FILE__)).'/'.$pageAlt.'.phtml')): ?>
                    <?= $this->render($variables, 'content/area/'.$pageAlt) ?>

                <?php else: ?>
                    <div umi:element-id="<?= $page->getId() ?>"
                         umi:field-name="content"
                         class="page-content">
                        <?= $pageContent ?>
                    </div>
                <?php endif; ?>

            <?php endif; ?>

        </div>
    </section>
</div>
