<?php
/**
 * Created by PhpStorm.
 * User: GermanWeb
 * Date: 23.10.2018
 * Time: 11:38
 */

$page = $variables['page'];

$pageContent = $page->getValue('content');

?>

<div class="map-page">
    <iframe src="http://pkk5.rosreestr.ru/#x=17352784.848305427&y=7463934.545514463&z=10&app=toc&opened=1" frameborder="no" height="440">
        Ваш браузер не поддерживает плавающие фреймы!
    </iframe>
</div>