<?php
/**
 * Лента новостей.
 *
 * @var umiTemplaterPHP|ViewPhpExtension|DemomarketPhpExtension $this
 * @var array $variables
 * @var iUmiHierarchyElement $rubric
 */

$settings = $this->getSettingsContainer('main_config');
$rubric = $variables['page'];
$newsList = $this->macros('news', 'lastlist');

?>

<?= $this->render($variables, 'layout/breadcrumbs') ?>

<div class="section_capt">
    <div class="container">
        <div class="row">
            <div class="logo">
                <?= $this->render(
                    [
                        'id' => $settings->getId(),
                        'field_name' => 'logo1',
                        'src' => $settings->getValue('logo1'),
                        'alt' => "logo",
                        'width' => 40,
                        'height' => 50,
                    ],
                    'library/thumbnail'
                ) ?>
            </div>

            <h1>
                Новости
            </h1>
        </div>

        <div class="title">
            <span class="flaticon-seo"></span>

            <h2>
                Раздел находится в разработке
            </h2>
        </div>
    </div>
</div>

<!--<div class="section_capt">-->
<!--	<div class="container">-->
<!--		<div class="row">-->
<!--			<h1 umi:element-id="--><?//= $rubric->getId() ?><!--" umi:field-name="h1"-->
<!--			    umi:empty="--><?//= $this->translate('empty_page_name') ?><!--">-->
<!--				--><?//= $rubric->getValue('h1') ?>
<!--			</h1>-->
<!--		</div>-->
<!--	</div>-->
<!--</div>-->
<!---->
<!--<div class="news" umi:button-position="top right" umi:element-id="--><?//= $rubric->getId() ?><!--" umi:region="list"-->
<!--     umi:module="news" umi:method="lastlist" umi:sortable="sortable">-->
<!--	<div class="container">-->
<!--		<div class="news_container">-->
<!--			--><?php //foreach ($newsList['lines'] as $newsItem): ?>
<!--				--><?//= $this->render($newsItem, 'news/rubric_item') ?>
<!--			--><?php //endforeach; ?>
<!--		</div>-->
<!---->
<!--		--><?//= $this->render($newsList, 'library/pagination') ?>
<!--	</div>-->
<!--</div>-->
