<?php
/**
 * Created by PhpStorm.
 * User: Alex
 * Date: 27.08.2019
 * Time: 17:22
 */
$page = $variables['page'];
$pageTitle = $page->getValue('h1');
?>

<div class="one-page__title">
    <h2>
        <?= $pageTitle ?>
    </h2>

    <!--    <a href="--><?//= $this->getPath($parentList[1]) ?><!--" class="button-back">-->
    <!--        <span class="flaticon-back arrow1"></span>-->
    <!--        <span class="flaticon-back arrow2"></span>-->
    <!--        <span class="flaticon-back arrow3"></span>-->
    <!--        <span class="button-text">Вернуться назад</span>-->
    <!--    </a>-->
</div>