<?php
/**
 * Created by PhpStorm.
 * User: Alex
 * Date: 27.08.2019
 * Time: 17:22
 */
$page = $variables['page'];
$page_id = $variables['pageId'];
$main_settings = $this->getSettingsContainer('main_config');
$no_image = '/templates/kamchatka_theme/images/noimage.jpeg';
$albumData = $this->macros('photoalbum', 'albums', ['default', INF, 0, '/page-gallery/','asc'])["items"];

$parentList = $variables['parents'];
$pageTitle = $page->getValue('h1');

$one_album= [];
foreach ($albumData as $key => $item) {
    $one_album[$key]['id'] = $item['id'];
    $one_album[$key]["name"] = $item["name"];
    $one_album[$key]["link"] = $item["link"];

    $image = $this->getPageById($item['id'])->getValue('header_pic');
    
    if(isset($image)) {
        $one_album[$key]["image"] = $image->getFilepath(true);
    } else {
        $one_album[$key]["image"] = $no_image;
    }

    $date = $this->getPageById($item['id'])->getValue('create_time');
    
    if(isset($date)) {
        $one_album[$key]["timestamp"] = $date;
    } else {
        $one_album[$key]["timestamp"] = date('U');
    }
}

function cmp($a, $b) {
    if ($a["timestamp"] == $b["timestamp"]) {
        return 0;
    }

    return ($a["timestamp"] > $b["timestamp"]) ? -1 : 1;
}

usort($one_album, "cmp");

?>

<div class="one-page__title">
    <h2>
        <?= $pageTitle ?>
    </h2>
</div>

<div class="one-page__body">
    <div class="gallery">
        <?php foreach ($one_album as $item): ?>
            <a class="gallery__item" href="<?= $item['link'] ?>">
                <img src="<?= $item['image'] ?>" alt="image">

                <p class="gallery__text"><?= $item["name"] ?></p>
            </a>
        <?php endforeach; ?>
    </div>
</div>