<?php
/**
 * Created by PhpStorm.
 * User: GermanWeb
 * Date: 12.08.2019
 * Time: 16:17
 */
$page = $variables['page'];
$pageId = $variables['pageId'];
$pageTitle = $page->getValue('h1');
$pageLink = $page->link;
$pageAlt = $page->getAltName();
$pageContent = $page->getValue('content');

$docList = $page->getValue('filter-doc');
if (count($docList) > 0) {
    foreach ($docList as $key => $item) {
        $oneDoc[$key]['name'] = $this->getObjectById($item)->name;
        $objDoc = $this->getObjectById($item)->getValue('file-doc');
        if (isset($objDoc)) {
            $oneDoc[$key]['doc'] = $objDoc->getFilePath(true);

        } else {
            $oneDoc[$key]['doc'] = 'javascript:void(0)';
        }
    }
}

$pageAntiCorruptionMenu = $this->macros('content', 'menu', array(null, 1, 692))['items'];

$pageAntiCorruption['id'] = 692;
$pageAntiCorruption['name'] = $this->getPageById(692)->getValue('h1');
$pageAntiCorruption['link'] = $this->getPageById(692)->link;

if ($pageLink == $pageAntiCorruption['link']) {
    $pageAntiCorruption['status'] = "active";
}

array_unshift($pageAntiCorruptionMenu, $pageAntiCorruption);

foreach ($pageAntiCorruptionMenu as $key => $item) {
    $secondaryMenu = $this->macros('content', 'menu', array(null, 1, $item['id']))['items'];

    if (count($secondaryMenu) >= 1 && $item['id'] !== 692) {
        $pageAntiCorruptionMenu[$key]['sub-menu'] = $secondaryMenu;
    }
}

?>

<?= $this->render($variables, 'content/header-pages') ?>

<div class="secondary-page anti-corruption-page">
    <nav>
        <div class="secondary-page__mobile-menu">
            <span class="flaticon-angle-arrow-down"></span>
        </div>

        <ul class="secondary-page__menu">
            <? foreach ($pageAntiCorruptionMenu as $key => $item):
                $itemLink = $item['link'];
                if ($item['id'] === '703') {
                    $itemLink = '/page-administration/page-collegiate/?anchor_anti_corruption=active#anchor_id_1';
                } else if ($item['id'] === '705') {
                    $itemLink = '/page-appeal/';
                } ?>

                <li class="secondary-page__item">
                    <a id="pageId-<?= $item['id'] ?>" class="<?= $item['status'] ?>" href="<?= $itemLink ?>">
                        <?= $item['name'] ?>
                    </a>

                    <? if (isset($item['sub-menu'])): ?>
                        <ul class="second-level-menu">
                            <? foreach ($item['sub-menu'] as $key2 => $item2): ?>
                                <li class="second-level-menu__item">
                                    <a id="pageId-<?= $item2['id'] ?>"
                                       class="inside-tabs-ajax-js <?= $item2['status'] ?>"
                                       href="<?= $item2['link'] ?>">
                                        <?= $item2['name'] ?>
                                    </a>
                                </li>
                            <? endforeach; ?>
                        </ul>
                    <? endif; ?>
                </li>
            <? endforeach; ?>
        </ul>
    </nav>

    <section class="one-page pageId-<?= $pageId ?>">
        <div class="to-insert-ajax-js">
            <div class="one-page__title">
                <h2>
                    <?= $pageTitle ?>
                </h2>
            </div>

            <? if ($pageId !== '702' && $pageId !== '704'): ?>
                <div class="one-page__body">
                    <?php if ($pageLink == $pageAntiCorruption['link']): ?>

                        <div umi:element-id="<?= $page->getId() ?>"
                             umi:field-name="content"
                             class="about-area">
                            <?= $pageContent ?>
                        </div>

                    <?php else: ?>

                        <?php if (file_exists(realpath(dirname(__FILE__)) . '/' . $pageAlt . '.phtml')): ?>
                            <?= $this->render($variables, 'content/anti-corruption/' . $pageAlt) ?>

                        <?php else: ?>
                            <div umi:element-id="<?= $page->getId() ?>"
                                 umi:field-name="content"
                                 class="page-content">
                                <?= $pageContent ?>
                            </div>
                        <?php endif; ?>

                    <?php endif; ?>

                    <? if (isset($oneDoc)): ?>
                        <div class="doc-list">
                            <h3>
                                Документы для скачивания
                            </h3>

                            <?php foreach ($oneDoc as $key => $item): ?>
                                <div class="one-tab">
                                    <div class="one-tab__title">
                                        <div class="left">
                                            <span class="flaticon-document"></span>

                                            <p>
                                                <?= $item['name'] ?>
                                            </p>
                                        </div>

                                        <div class="right">
                                            <div class="doc-load">
                                                <a href="<?= $item['doc'] ?>" download="">
                                                    Скачать файл
                                                    <span class="flaticon-back"></span>
                                                </a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            <?php endforeach; ?>
                        </div>
                    <? endif; ?>
                </div>

            <? elseif ($pageId === '702' || $pageId === '704'): ?>
                <?= $this->render($variables, 'content/administration/page-work-plan/page-work-plan') ?>
            <? endif; ?>
        </div>
    </section>
</div>
