<?php
/**
 * Основной контент страницы.
 *
 * @var umiTemplaterPHP|ViewPhpExtension|DemomarketPhpExtension $this
 * @var array $variables
 */
$pageId = $variables['pageId'];
?>

<main>
    <? if ($pageId != 83) {
        echo $this->render($this->macros('system', 'listErrorMessages'), 'library/errors');
    } ?>

    <?= $this->render($variables, "{$variables['module']}/{$variables['method']}") ?>
</main>